### ISSUE TITLE
Question for BioRED corpus preprocess for relation extraction task.

### ISSUE THREAD

**Issue by li-muz** [ncbi/BioRED#4]
Hello, I am researching the corpus preprocessing methods you used in your relation extraction tasks. I noticed that when creating instances, you added special markers "@DiseaseOrPhenotypicFeatureSrc$" or "@DiseaseOrPhenotypicFeatureTgt$" before and after the entities. However, while studying the corpus, I found that the BioRED corpus did not distinguish the directionality between entity pairs, nor did it specify how to distinguish entities as "source" and "target". Could you please clarify what "source entity" and "target entity" refer to in this context?
Thanks.

**Comment by ptlai** [comment]
Hi @li-muz ,

The terms "Src" and "Tgt" do not indicate the direction of the relationship in our case. 

- For entity pairs with different entity types. 'Src' and 'Tgt' are fixed for a pair of entities. In the case of chemical-disease pairs, "ChemicalEntitySrc" and "DiseaseOrPhenotypicFeatureTgt" are used.

- For entity pairs with the same entity type. "Src" and "Tgt" are assigned according to the order in which the entity pairs appear within the abstract. A label "Src" is assigned to the first entity mentioned, while a label "Tgt" is assigned to the second entity mentioned.

Po-Ting

**Comment by li-muz** [comment]
Thanks for your answers,
